sylius_grid:
    grids:
        setono_sylius_shop_the_look_admin_look:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_shop_the_look.model.look.class%"
                    repository:
                        method: createListQueryBuilder
            sorting:
                position: asc
            limits: [25, 50, 100]
            fields:
                position:
                    type: twig
                    label: sylius.ui.position
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/position.html.twig"
                type:
                    type: string
                    label: sylius.ui.type
                    sortable: ~
                    position: 20
                code:
                    type: string
                    label: sylius.ui.code
                    sortable: ~
                name:
                    type: string
                    label: setono_sylius_shop_the_look.ui.name
                parts:
                    type: twig
                    label: setono_sylius_shop_the_look.ui.parts
                    options:
                        template: "@SetonoSyliusShopTheLookPlugin/admin/grid/field/parts.html.twig"
                discount:
                    type: string
                    label: sylius.ui.discount
                    sortable: ~
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    sortable: ~
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            filters:
                search:
                    type: string
                    label: sylius.ui.search
                    options:
                        fields: [code, translations.name]
                enabled:
                    type: boolean
                    label: sylius.ui.enabled
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
                bulk:
                    delete:
                        type: delete
