setono_sylius_shop_the_look_admin_ajax_look:
    resource: "@SetonoSyliusShopTheLookPlugin/Resources/config/routes/admin/ajax.yaml"
    prefix: /ajax/look

setono_sylius_shop_the_look_admin_look:
    resource: |
        alias: setono_sylius_shop_the_look.look
        section: admin
        templates: "@SyliusAdmin\\Crud"
        redirect: index
        grid: setono_sylius_shop_the_look_admin_look
        vars:
            all:
                subheader: setono_sylius_shop_the_look.ui.manage_looks
                templates:
                    form: "@SetonoSyliusShopTheLookPlugin/admin/look/_form.html.twig"
            index:
                icon: 'images outline'
    type: sylius.resource
