setono_sylius_shop_the_look_admin:
    resource: "@SetonoSyliusShopTheLookPlugin/Resources/config/routes/admin.yaml"
    prefix: /admin

setono_sylius_shop_the_look_shop:
    resource: "@SetonoSyliusShopTheLookPlugin/Resources/config/routes/shop.yaml"
    prefix: /
