setono_sylius_shop_the_look_admin:
    resource: "@SetonoSyliusShopTheLookPlugin/Resources/config/routes/admin.yaml"
    prefix: /admin

setono_sylius_shop_the_look_shop:
    resource: "@SetonoSyliusShopTheLookPlugin/Resources/config/routes/shop.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$
