imports:
    - { resource: "@SetonoSyliusShopTheLookPlugin/Resources/config/grids/setono_sylius_shop_the_look_admin_look.yaml" }
    - { resource: "@SetonoSyliusShopTheLookPlugin/Resources/config/grids/setono_sylius_shop_the_look_shop_look.yaml" }

sylius_ui:
    events:
        setono_sylius_shop_the_look.admin.look.create.javascripts:
            blocks:
                javascript: "@SetonoSyliusShopTheLookPlugin/admin/look/javascript.html.twig"
        setono_sylius_shop_the_look.admin.look.update.javascripts:
            blocks:
                javascript: "@SetonoSyliusShopTheLookPlugin/admin/look/javascript.html.twig"
