sylius_fixtures:
    suites:
        default:
            fixtures:

                setono_look_with_random_products_1:
                    name: setono_look
                    options:
                        custom:
                            look_1:
                                name: 'Look with 3 random products per part'
                                discount: 20
                                position: 2
                                images:
                                    - { path: '@SyliusCoreBundle/Resources/fixtures/adminAvatars/luke.jpg' }
                                parts:
                                    - 'Hat'
                                    - 'Jacket'
                                    - 'Pants'

                setono_look_with_random_products_2:
                    name: setono_look
                    options:
                        custom:
                            look_1:
                                name: 'Look with random products'
                                discount: 10
                                position: 1
                                images:
                                    - { path: '@SyliusCoreBundle/Resources/fixtures/adminAvatars/luke.jpg' }
                                parts: 
                                    -   name: 'Hat'
                                        position: 3
                                    -   name: 'Jacket'
                                        products: 2
                                        position: 1
                                    -   name: 'Pants'
                                        products: 1
                                        position: 2

                setono_look_with_specific_products:
                    name: setono_look
                    options:
                        custom:
                            look_1:
                                code: 'eco'
                                discount: 30
                                position: 20
                                name: 'Eco cap look'
                                description: 'Look with eco cap'
                                slug: 'eco-cap'
                                translations:
                                    de_DE:
                                        name: 'Öko-kappe aussehen'
                                images:
                                    # More images to check lightbox works well
                                    - { path: '@SyliusCoreBundle/Resources/fixtures/adminAvatars/john.jpg' }
                                    - { path: '@SyliusCoreBundle/Resources/fixtures/adminAvatars/luke.jpg' }
                                    - { path: '@SyliusCoreBundle/Resources/fixtures/adminAvatars/john.jpg' }
                                    - { path: '@SyliusCoreBundle/Resources/fixtures/adminAvatars/john.jpg' }
                                    - { path: '@SyliusCoreBundle/Resources/fixtures/adminAvatars/luke.jpg' }
                                parts:
                                    -   name: 'Cap'
                                        products:
                                            # Slug of 'Knitted white pompom cap'
                                            # from vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/cap.yaml
                                            - 'knitted_white_pompom_cap'
                                            # Slug of 'Knitted burgundy winter cap'
                                            - 'knitted_burgundy_winter_cap'
                                    -   name: 'Jeans'
                                        products:
                                            # Slug of '000F office grey jeans'
                                            # from vendor/sylius/sylius/src/Sylius/Bundle/CoreBundle/Resources/config/app/fixtures/jeans.yaml
                                            - '000F_office_grey_jeans'

                setono_look_disabled:
                    name: setono_look
                    options:
                        random: 3
                        prototype:
                            images:
                                - type: 'slide'
                                  path: '@SyliusCoreBundle/Resources/fixtures/adminAvatars/luke.jpg'
                            parts:
                                - name: 'One'
                                - name: 'Two'
                                - name: 'Three'
                            position: 10
                            enabled: false
